name: build-artifacts

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get required Java version
        id: gradle-properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: java_version

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ steps.gradle-properties.outputs.java_version }}

      - name: Build artifacts
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs

      - name: Global gradle caches
        uses: actions/cache@v4.1.0
        with:
          path: ~/.gradle
          key: global-gradle-cache

      - name: Build caches
        uses: actions/cache@v4.1.0
        with:
          path: ./.gradle
          key: build-gradle-cache
        
